### ISSUE TITLE
Update rang to v2

### ISSUE THREAD

**Issue by agauniyal** [longlene/clx#3]
Found rang lib mentioned here - `clx/dev-cpp/rang/rang-1.0.ebuild`. v2 has been released, thought you might be interested in updating the version.

https://github.com/agauniyal/rang

**Comment by longlene** [comment]
@agauniyal Thanks! I've updated it.  https://github.com/longlene/clx/commit/8bf685e7ec852f48198cb6e5b48dca8282639602 :-D
