### ISSUE TITLE
importing srslte into gentoo

### ISSUE THREAD

**Issue by ZeroChaos-** [longlene/clx#5]
I used your ebuild as a basis and imported net-wireless/srslte into gentoo.  Thanks for your work, and you are most welcome to help maintain if you would like.

You may remove srslte from your overlay (or not, your choice).

I did notice that ~200 of the tests fail for me on this release.  Is that typical?

**Comment by ZeroChaos-** [comment]
You also may want my changes if you choose to keep your ebuild
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=408388ecfb5bfabddb38880a3be637a9b3e09af1

**Comment by longlene** [comment]
Glad to see it in gentoo main portage.
I'll remove it in this repo :-)
